{
 "title": "Health - Microservices",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "microservice",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"apps\"},workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests to server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"${microservice}\"} |= \"request\" |= \"method=GET\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total status 500 response",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"${microservice}\"} |~ \"status=500\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"${microservice}\"} | json | level=\"ERROR\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Server Request Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"${microservice}\"} |~ \"status=500\" [$__range])) / sum(count_over_time({app=~\"${microservice}\"} |= \"request\" |= \"method=GET\" [$__range])) * 100"
    }
   ]
  },
  {
   "title": "Total Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{container=\"${microservice}-container\"})"
    }
   ]
  },
  {
   "title": "Total request avg latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"basic-app\"} |= \"duration\" | json | regexp \"duration=(?P<duration_ms>\\\\d+) ms\" | unwrap duration_ms[$__range]))"
    }
   ]
  },
  {
   "title": "Successful requests avg latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"basic-app\"} |= \"duration\" |= \"200\" | json | regexp \"duration=(?P<duration_ms>\\\\d+) ms\" | unwrap duration_ms[$__range]))"
    }
   ]
  },
  {
   "title": "Avg Latency status 500 requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"basic-app\"} |= \"duration\" |= \"500\" | json | regexp \"duration=(?P<duration_ms>\\\\d+) ms\" | unwrap duration_ms[$__range]))"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"apps\", pod=~\"${microservice}.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Faulty pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"apps\", pod=~\"basic-app.*\", phase=~\"Pending|Failed|Unknown\"} > 0) by (pod)"
    }
   ]
  }
 ]
}