grafana:
  enabled: false

prometheus:
  service:
    type: "ClusterIP"
  prometheusSpec:
    storageSpec:
      emptyDir: {}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: NodeType
                  operator: In
                  values:
                    - apps
    retention: 30d
    startupProbe:
      httpGet:
        path: /-/ready
        port: http-web
        scheme: HTTP
      timeoutSeconds: 20
      periodSeconds: 25
      successThreshold: 1
      failureThreshold: 300
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 400m
        memory: 800Mi
    additionalScrapeConfigs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: pod
                label: "app.kubernetes.io/name=traefik"
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\\d+)?;(\\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: traefik
      - job_name: k8s-kube-state-metrics-cluster-prod
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ['IP:PORT']
        metric_relabel_configs:
        - target_label: cluster
          replacement: cluster-prod
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
